# load libraries and set working directory to repo
library(rvest)
library(tidyr)
library(stringr)
setwd("~/G_WD/SIF_scrape")

# read html file generated by phantomjs
html = read_html('espn.html')


# scrape game ids
print("scraping espn game ids...")

egame_id = html %>%
    html_nodes(".scoreboard") %>%
    html_attr("id")
egame_id = na.omit(egame_id)
egame_id = as.integer(egame_id)

print("COMPLETE")        


# scrape scores
print("scraping espn scores...")
scores = numeric(0)

for(i in egame_id){
    score = html %>%
        html_nodes(paste("#", i,  " .total", sep = "")) %>%
        html_text()
    score = score[2:3]
    scores = append(scores, score)
    
}
scores = as.numeric(scores)
scores = as.data.frame(cbind(away_score = scores[c(TRUE,FALSE)], 
                             home_score = scores[c(FALSE,TRUE)]), 
                       stringsAsFactors = FALSE)
print("COMPLETE")


# bind together into games table
print("binding games table...")

games = as.data.frame(cbind(egame_id, 
                            scores),
                      stringsAsFactors = FALSE)

print("COMPLETE") 

map = read.csv("./maps/map1.csv", header = TRUE, stringsAsFactors = FALSE)[,1:2]
espn = read.csv(
    paste(out_path, "/espn_", Sys.Date(), ".csv", sep = ""))[,c("game_id",
                                                                "favorite",
                                                                "espn_spread")]
games = merge(map, games, by = "egame_id")
games = merge(games, espn, by = "game_id")
games$winner = colnames(games[,c("away_score", "home_score")])[max.col(
                games[,c("away_score", "home_score")],ties.method="first")]
games$winner = gsub("_score", "", winner)

games$upset_flag = ifelse(games$favorite == "", "", 
                            ifelse(is.na(match(games$favorite, games$away_short)), 
                                   "away", "home"))

