# load libraries and set working directory to repo
library(rvest)
library(tidyr)
library(stringr)
setwd("~/G_WD/SIF_scrape")

# run phantomjs javascript file to render javascript variables and save as html in working directory
system("./phantomjs scrape_espn.js")

# read html file generated by phantomjs
html = read_html('espn.html')

# scrape week
week_raw = "Week 1, 2017"

# scrape teams
teams_raw = html %>%
    html_nodes(".sb-team-short") %>%
    html_text()
teams = as.data.frame(cbind(away = teams_raw[c(TRUE,FALSE)], 
                            home = teams_raw[c(FALSE,TRUE)]), 
                      stringsAsFactors = FALSE)

# scrape team short names
shorts_raw = html %>%
    html_nodes(".sb-team-abbrev") %>%
    html_text()
shorts = as.data.frame(cbind(away_short = shorts_raw[c(TRUE,FALSE)], 
                             home_short = shorts_raw[c(FALSE,TRUE)]),
                       stringsAsFactors = FALSE)

# scrape espn game ids
egame_id = html %>%
    html_nodes(".scoreboard") %>%
    html_attr("id")
egame_id = na.omit(egame_id)
egame_id = as.integer(egame_id)

# scrape dates
dates = html %>%
    html_nodes(".date-time") %>%
    html_attrs() 
dates = unlist(lapply(test, '[[', 3))
dates = gsub("T", " ", dates)
dates = gsub("Z", "", dates)
dates = as.POSIXlt(dates)

# bind together into games table
games = as.data.frame(cbind(egame_id, dates, teams, shorts), stringsAsFactors = FALSE)


# loop for espn game ids and lines
lines = character(0)

for(i in game_id){
    line = html %>%
        html_nodes(paste("#", i,  " .line", sep = "")) %>%
        html_text()
    line = paste(i, line, sep = " ")
    lines = append(lines, line)
}
lines = as.data.frame(str_split_fixed(lines, " ", 3),
                        stringsAsFactors = FALSE)
colnames(lines) = c("egame_id", "favorite", "spread")

# merge all into spreads table
spreads = merge(games, lines, by = "egame_id", all.x = TRUE)

# add timestamp columns
spreads$update_ts = Sys.time()

# output to .csv
write.csv(spreads, paste("./output/", week_raw,"/Spreads_", Sys.Date(),".csv", sep = ""), 
          row.names = FALSE)