# load libraries and set working directory to repo
library(rvest)
library(tidyr)
setwd("~/G_WD/SIF_scrape")

# run phantomjs javascript file to render javascript variables and save as html in working directory
system("./phantomjs scrape_espn.js")

# read html file generated by phantomjs
html = read_html('espn.html')

# scrape week
teams_raw = html %>%
    html_nodes(".sb-team-short") %>%
    html_text()
games = as.data.frame(cbind(teams_raw[c(TRUE,FALSE)], teams_raw[c(FALSE,TRUE)]))

shorts_raw = html %>%
    html_nodes(".sb-team-abbrev") %>%
    html_text()
shorts = as.data.frame(cbind(shorts_raw[c(TRUE,FALSE)], shorts_raw[c(FALSE,TRUE)]))

spread_raw = html %>%
    html_nodes(".line") %>%
    html_text()
spread = as.data.frame(str_split_fixed(spread_raw, " ", 2))

# bind scrapes into dataframe
spreads = as.data.frame(cbind(games, shorts), stringsAsFactors = FALSE)
colnames(spreads) = c("away", "home", "away_short", "home_short")
spreads = merge(spreads, spread, by.x = c("away_short"), by.y = c("V1"), all.x = TRUE)
spreads = merge(spreads, spread, by.x = c("home_short"), by.y = c("V1"), all.x = TRUE)
spreads = unite(spreads, spread, c("V2.x", "V2.y"), sep="")
spreads$spread = gsub("NA", "", spreads$spread)
spreads$spread = abs(as.numeric(spreads$spread))
spreads[is.na(spreads)] = ""
spreads$games = paste(spreads$away, spreads$home)

# read teams and games mapping tables
teams = read.csv('teams.csv', stringsAsFactors = FALSE)[, c('team_id', 'espn_team_name')]
games = read.csv('games.csv', stringsAsFactors = FALSE)[, c('game_id', 'home_id', 'away_id')]
games = merge(games, teams, by.x = 'away_id' , by.y = 'team_id')
games = merge(games, teams, by.x = 'home_id', by.y = 'team_id')
games$games = paste(games$espn_team_name.x, games$espn_team_name.y)

spreads = merge(spreads, games[,c('game_id', 'games')], by = 'games')
spreads = spreads[,c("game_id", "spread")]
spreads = spreads[order(spreads$game_id),]

# add underdog, week, and timestamp columns
spreads$update_ts = Sys.time()

# output to .csv
write.csv(spreads, paste("./output/", week_raw,"/Spreads_", Sys.Date(),".csv", sep = ""), row.names = FALSE)