# load libraries and set working directory to repo
library(rvest)
library(plyr)
library(stringr)
setwd("~/G_WD/SIF_scrape")

# run phantomjs javascript file to render javascript variables and save as html in working directory
system("./phantomjs scrape_oddshark.js")

# read html file generated by phantomjs
html = read_html('oddshark.html')

# scrape teams
team = html %>%
    html_nodes(".city") %>%
    html_text()

# scrape nick-name
nick_name = html %>%
    html_nodes(".nick-name") %>%
    html_text

# scrape lines
line = html %>%
    html_nodes(".value") %>%
    html_text()

spreads = as.data.frame(cbind(team, line), stringsAsFactors = FALSE)
spreads$line = gsub("EV", 0, spreads$line)
spreads$line = as.numeric(spreads$line)
spreads$underdog = as.integer(as.logical(spreads$line > 0))
spreads$timestamp = Sys.time()

# output to .csv
write.csv(spreads, paste("./output/Spreads_", Sys.Date(),".csv", sep = ""), row.names = FALSE)

